# curl -X 'GET'
#  'http://localhost:8080/api/debug/everything'
#  -H 'accept: */*'
GET http://localhost:8080/api/debug/everything
accept: */*

###

# curl -X 'GET'
#  'http://localhost:8080/api/reservation/session/dates'
#  -H 'accept: */*'
GET http://localhost:8080/api/reservation/session/dates
accept: */*

###

# curl -X 'POST'
#  'http://localhost:8080/api/reservation/seat/301/book'
#  -H 'accept: */*'
#  -H 'Content-Type: application/json'
#  -d '{
#  "firstName": "Max",
#  "lastName": "Mustermann",
#  "dob": "2000-01-03",
#  "city": "Leonding",
#  "zip": 4060,
#  "street": "Leondinger Straße",
#  "streetNo": 10,
#  "mail": "a@b.com"
#}'
POST http://localhost:8080/api/reservation/seat/301/book
accept: */*
Content-Type: application/json

{
  "firstName": "Max",
  "lastName": "Mustermann",
  "dob": "2000-01-03",
  "city": "Leonding",
  "zip": 4060,
  "street": "Leondinger Straße",
  "streetNo": 10,
  "mail": "a@b.com"
}

###

